#+TITLE: emacs configuration
#+AUTHOR: Lukas Grassauer
#+LANGUAGE: en

* Overview

This emacs configuration is the second attempt to create a working
emacs configuration.

The original version was very cluttered with stuff I didn't really
need, and so it became very unhandy to add new configuration. I did
still like the idea of literate programming so it becomes easier to
retroperspectivly understand what I was thinking.

I mostly want the emacs environment to function as my fallback
integrated development environment when there is no suiteable
alternative. Maybe this will change in the future.  I also want it to
be my primary =org-mode= and LaTeX editor.


* Sensible Defaults

I like the [[https://harryrschwartz.com/2015/11/23/sensible-defaults-el.html][philosophy]] behind [[https://github.com/hrs/sensible-defaults.el][sensible-defaults]], so I'm using it
#+BEGIN_SRC emacs-lisp

(load-file "~/.emacs.d/sensible-defaults.el")
(sensible-defaults/use-all-settings)
(sensible-defaults/use-all-keybindings)
(sensible-defaults/backup-to-temp-directory)

#+END_SRC


* Package handling

The =Cask= + =pallet= way of handling the persistent installation of
packages.  =Cask= is for handling information similar to the
=package.json= in Node.js and =pallet= is an emacs extension to work
with packages.

The following code enables emacs to work with the =cask= command. It
also requires =pallet= to be loaded.
#+BEGIN_SRC emacs-lisp

  (require 'cask "~/.cask/cask.el")
  (cask-initialize)
  (require 'pallet)

#+END_SRC

Fetches the latest org-mode

#+BEGIN_SRC emacs-lisp

  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/") t)
  (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)

  (add-to-list 'load-path "~/.emacs/opt/org-mode/lisp")
  (add-to-list 'load-path "~/.emacs/opt/org-mode/contrib/lisp" t)

  (package-initialize)
  (setq package-enable-at-startup nil)

#+END_SRC


* Visual Stuff

** Theme

#+BEGIN_SRC emacs-lisp

  (when window-system
   (load-theme 'idea-darkula t))

#+END_SRC


** Syntax Highlighting

Syntax highlighting is probably one of the few things every developer
agrees on.  Anyway, since Emacs 22.1 syntax highlighting is enabled by
[[https://www.gnu.org/software/emacs/manual/html_node/efaq/Turning-on-syntax-highlighting.html][default]].
*** =org-mode= =src=-Blocks
There is a neat little feature in =org-mode=. It supports literate
programming via ~source-blocks~. In fact this document is written in
/literate emacs-lisp/

To effectifly use this feature it's important (for me at least) to
activate syntax highlighting in those ~source-blocks~. It should be
enabled with this block of code:
#+BEGIN_SRC emacs-lisp

  (setq org-src-fontify-natively t)

#+END_SRC


** Symbols

*** Fancy lamdas

This renders pretty versions of some symbols
#+BEGIN_SRC emacs-lisp

  (global-prettify-symbols-mode t)

#+END_SRC


** UI

*** Disable scrollbar

I won't use it anyways, thanks to evil

#+BEGIN_SRC emacs-lisp

  (when window-system
   (scroll-bar-mode -1))

#+END_SRC

*** Enable current line highlighting

I want to quickly identify where the cursor is, this line should enable this behavior

#+BEGIN_SRC emacs-lisp

  (when window-system
    (global-hl-line-mode))

#+END_SRC


** Scrolling

When the cursor leaves the window, the editor recenters the buffer point. I
think that is rather hindering
#+BEGIN_SRC emacs-lisp

  (setq scroll-conservatively 100)

#+END_SRC


* Textmanipulation

** Evil

The /*e*xtensible *vi* *l*ayer/ (short evil) is undoubtly (well, it's my opinion after all) the single
best invention for emacs there is. It enables vi(m) keybindings for emacs.

Of course I like to have it enabled everywhere:
#+BEGIN_SRC emacs-lisp
(evil-mode 1)
#+END_SRC


** Line Wrap

I enjoy the auto linewrapping or autofilling (in emacs jargon). This
uses =M-q= everytime I write something (so to say).
#+BEGIN_SRC emacs-lisp

(add-hook 'text-mode-hook 'turn-on-auto-fill)
(add-hook 'gfm-mode-hook 'turn-on-auto-fill)
(add-hook 'org-mode-hook 'turn-on-auto-fill)

#+END_SRC

To deactivate it I prefer to =M-x auto-fill-mode=


* Coding

** Haskell

=Haskell-mode= should be sufficient for programming in =Haskell=. Though it's
nice to add smart indent and =haskell-doc-mode=
#+BEGIN_SRC emacs-lisp

(add-hook 'haskell-mode-hook
          (lambda ()
            (haskell-doc-mode)
            (turn-on-haskell-indent)
            (ghc-init)))

#+END_SRC


** Org-Mode

Org-ref & bibtex
#+BEGIN_SRC emacs-lisp

(require 'org-ref)

(setq reftex-default-bibliography '("~/Documents/bibliography/grassauer.bib"))
(setq org-ref-default-bibliography '("~/Documents/bibliography/grassauer.bib"))

#+END_SRC


#+BEGIN_SRC emacs-lisp

(eval-after-load "org"
  '(require 'ox-md nil t))

#+END_SRC

ispell ignore org-mode constructs

#+BEGIN_SRC emacs-lisp

(add-to-list 'ispell-skip-region-alist '(":\\(PROPERTIES\\|LOGBOOK\\):" . ":END:"))
(add-to-list 'ispell-skip-region-alist '("#\\+BEGIN_SRC" . "#\\+END_SRC"))

#+END_SRC

enable spellchecking and grammarchecking

#+BEGIN_SRC emacs-lisp

(add-hook 'org-mode-hook (lambda ()
   (progn
     ;; Snipped
     (auto-fill-mode t)

     ;; Spelling
     (flyspell-mode t)

     ;; Grammar
     (require 'langtool)
     (setq langtool-java-classpath "/opt/LanguageTool-3.9/:/opt/LanguageTool-3.9/*:/usr/share/java/languagetool/*"))))

#+END_SRC

latex export:

#+BEGIN_SRC emacs-lisp

(setq org-export-with-smart-quotes t)

(setq org-latex-pdf-process
'("pdflatex %f" "bibtex %b" "pdflatex %f" "pdflatex %f"))

#+END_SRC


* Settings

** Editor

*** Spaces over tabs

I prefer spaces over tabs.
#+BEGIN_SRC emacs-lisp

  (setq-default indent-tabs-mode nil)

#+END_SRC

*** Indentation

The width-masterrace speaks through me
#+BEGIN_SRC emacs-lisp

  (setq-default tab-width 2)

#+END_SRC

*** Allow dead-keys

(require 'iso-transl)

** Visual Bell

Disable the visual bell (I think it does not help in any way)
#+BEGIN_SRC emacs-lisp

  (setq ring-bell-function 'ignore)

#+END_SRC
