add_newline = false

format = """\
    $username\
    $hostname\
    $kubernetes\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $hg_branch\
    $package\
    $dotnet\
    $golang\
    $java\
    $nodejs\
    $php\
    $python\
    $ruby\
    $rust\
    $terraform\
    $nix_shell\
    $conda\
    $memory_usage\
    $aws\
    $env_var\
    $cmd_duration\
    $line_break\
    $jobs\
    $battery\
    $time\
    $character\
    """

scan_timeout = 5

[aws]
disabled = true

[battery]
disabled = true

[character]
success_symbol = "[λ](blue)"
error_symbol = "[φ](bold red)"
vicmd_symbol = "[β](yellow)"
disabled = false

[cmd_duration]
min_time = 10000
show_milliseconds = true
style = "yellow"
format = "[$duration]($style)"
disabled = false

[conda]
disabled = false

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncate_to_repo = false
disabled = false

[dotnet]
disabled = true

[env_var]
disabled = true

[git_branch]
format = "on [$branch]($style) "
disabled = false

[git_commit]
format = "[\\($hash\\)]($style) [$tag]($style)"
style = "white"
only_detached = false
tag_disabled = false
tag_symbol = ""
disabled = false

[git_state]
disabled = false

[git_status]
style = "white"
format = '([\($all_status$ahead_behind\)]($style) )'
conflicted = "[=$count](red)"
untracked = "[?$count](blue)"
stashed = '[\$$count](yellow)'
modified = "[!$count](cyan)"
staged = "[+$count](green)"
renamed = "[>>$count](purple)"
deleted = "[-$count](red)"
ahead = "^${count}"
diverged = "^${ahead_count}v${behind_count}"
behind = "v${count}"
disabled = false

[golang]
disabled = false

[hg_branch]
disabled = true

[hostname]
disabled = false

[jobs]
disabled = false

[kubernetes]
disabled = true

[line_break]
disabled = false

[nix_shell]
disabled = true

[java]
disabled = true

[memory_usage]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[php]
disabled = true

[python]
pyenv_version_name = true
disabled = false

[ruby]
disabled = true

[rust]
disabled = true

[terraform]
disabled = true

[time]
disabled = true

[username]
disabled = false
