#!/bin/bash

(printf   "############\n# dotfiles #\n############\n\n" > /tmp/dotfiles.log && cd ~/dotfiles && ((git pull --stat --ff-only >> /tmp/dotfiles.log) || (git pull --rebase --stat >> /tmp/dotfiles.log) || (git rebase --abort >> /tmp/dotfiles.log)) && cd ~) &
DOTFILEPID=($!)
(printf "\n############\n#   apt    #\n############\n\n" > /tmp/apt.log && (sudo apt-get update >> /tmp/apt.log) && (sudo apt-get upgrade -y >> /tmp/apt.log)) &
APTPID=($!)
(printf "\n############\n# neofetch #\n############\n\n" > /tmp/neofetch.log && neofetch >> /tmp/neofetch.log) &
NEOFETCHPID=($!)
############
# dotfiles #
############
tail --quiet --lines=+0 --follow=dotfiles --retry --pid=$DOTFILEPID /tmp/dotfiles.log
wait "$DOTFILEPID"
############
#   apt    #
############
tail --quiet --lines=+0 --follow=apt --retry --pid=$APTPID /tmp/apt.log
wait "$APTPID"
############
# neofetch #
############
tail --quiet --lines=+0 --follow=neofetch --retry --pid=$NEOFETCHPID /tmp/neofetch.log
wait "$NEOFETCHPID"

# final wait to be sure everything is done
wait
