name: Linux

on:
  push:
    paths:
      - "bootstrap.sh"
      - "git/**"
      - "install.sh"
      - "vim/**"
      - "zsh/**"
      - "*.packages"
    tags:
  workflow_dispatch:

jobs:
  ubuntu_2004:
    name: 🐧 Linux Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Run bootstrap.sh
        run: ./bootstrap.sh --verbose --verbose
      - name: Run install.sh
        run: ./install.sh
  ubuntu_2204:
    name: 🐧 Linux Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Run bootstrap.sh
        run: ./bootstrap.sh --verbose --verbose
      - name: Run install.sh
        run: ./install.sh
  fedora_37:
    name: 🐧 Linux Fedora 37
    runs-on: ubuntu-latest
    container: fedora:37
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Run bootstrap.sh
        run: ./bootstrap.sh --verbose --verbose --no-ghcup
      - name: Run install.sh
        run: ./install.sh
