name: Test

on:
  push:
    paths:
      - "**.sh"
      - "**zsh*"
      - "**rc"
      - "**.toml"
      - "**.git*"

jobs:
  check_shell:
    name: 🐚 Check Shell Files
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Check if file bootstrap.sh exist
        shell: bash
        run: file -f bootstrap.sh
      - name: Check if file install.sh exist
        shell: bash
        run: file -f install.sh
      - name: Run ShellCheck on [bootstrap.sh,install.sh]
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          ignore: >-
            git
            vim
            zsh
      - name: Check if file zsh/.zshenv exist
        shell: bash
        run: file -f zsh/.zshenv
      - name: Check if file zsh/.zshrc exist
        shell: bash
        run: file -f zsh/.zshrc
      - name: Run ShellCheck on [zsh/*]
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          additional_files: >-
            zsh/.zshenv
            zsh/.zshrc
          ignore: >-
            bootstrap.sh
            install.sh
  check_toml:
    name: 📝 Check TOML Files
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Check if file zsh/.config/starship.toml exists
        shell: bash
        run: test -f zsh/.config/starship.toml
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip
      - name: Install TOML Validator
        shell: bash
        run: python3 -m pip install --upgrade --user toml-validator
      - name: Validate TOML [zsh/.config/starship.toml]
        shell: bash
        run: toml-validator zsh/.config/starship.toml
  check_gitconfig:
    name: 🔻 Check Gitconfig
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Check if file git/.gitconfig exists
        shell: bash
        run: test -f git/.gitconfig
      - name: Validate git/.gitconfig
        shell: bash
        run: git config --file git/.gitconfig --list
  check_vimrc:
    name: ⌨️ Check vimrc
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Check if file vim/.vimrc exists
        shell: bash
        run: test -f vim/.vimrc
      - name: Validate vim/.vimrc
        shell: bash
        run: vim -u NONE -c 'try | source vim/.vimrc | catch | cq | endtry | q'
  check_emacs:
    name: 📝 Check Emacs
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        name: Check if directory emacs/.emacs.d exists
        shell: bash
        run: test -d emacs/.emacs.d/
      - name: Ensure emacs
        uses: sudo apt-get install -y emacs
      - name: Validate emacs/.emacs.d
        shell: bash
        run: env HOME=./emacs emacs --debug-init --batch
