name: Test

on:
  push:
    paths:
      - "**.sh"
      - "**zsh*"
      - "**rc"
      - "**.toml"
      - "**.git*"

jobs:
  check_shell:
    name: 🐚 Check Shell Files
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Run ShellCheck on [bootstrap.sh,install.sh]
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          ignore: >-
            git
            vim
            zsh
      - name: Run ShellCheck on [zsh/*]
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          additional_files: >-
            zsh/.zshenv
            zsh/.zshrc
          ignore: >-
            bootstrap.sh
            install.sh
  check_toml:
    name: 📝 Check TOML Files
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip
      - name: Install TOML Validator
        shell: bash
        run: python3 -m pip install --upgrade --user toml-validator
      - name: Validate TOML [zsh/.config/starship.toml]
        shell: bash
        run: toml-validator zsh/.config/starship.toml
  check_gitconfig:
    name: 🔻 Check Gitconfig
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Validate git/.gitconfig
        shell: bash
        run: git config --file git/.gitconfig --list
  check_vimrc:
    name: ⌨️ Check vimrc
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Create test.vim
        shell: bash
        run: echo "try\n  source vim/.vimrc\n  quit\ncatch\n  cquit\nendtry" > test.vim
      - name: Validate vim/.vimrc
        shell: bash
        run: vim -E -s -u test.vim
